<?php 

defined("SUAP_CLASS") OR define("SUAP_CLASS",1);

defined('SUAP_CLIENT_ID')		||  define('SUAP_CLIENT_ID','YOUR_CLIENT_ID');

defined('SUAP_CLIENT_SECRET')		|| define('SUAP_CLIENT_SECRET','YOUR_CLIENT_SECRET');

defined("SUAP_REDIRECT_URI") OR define("SUAP_REDIRECT_URI",'YOUR_REDIRECT_URI');
